// Generated by `bun init`

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.png" {
  const path: string;
  export default path;
}

declare module "*.jpg" {
  const path: string;
  export default path;
}

declare module "*.jpeg" {
  const path: string;
  export default path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}

declare module "*.md" {
  const MDXContent: import("react").ComponentType<{
    components?: Record<string, import("react").ComponentType<Record<string, unknown>>>;
  }>;
  export default MDXContent;
  export const metadata: { size: string; lastModified: string; path: string } | undefined;
  export const raw: string | undefined;
}

declare module "*.mdx" {
  const MDXContent: import("react").ComponentType<{
    components?: Record<string, import("react").ComponentType<Record<string, unknown>>>;
  }>;
  export default MDXContent;
  export const metadata: { size: string; lastModified: string; path: string } | undefined;
  export const raw: string | undefined;
}
