// Generated by `bun init`

declare namespace NodeJS {
  interface ProcessEnv {
    BUN_PUBLIC_CONVEX_URL?: string;
    CONVEX_URL?: string;
  }
}

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}
