export { ACTIVE_ENTITLEMENT_SQL, ACTIVE_GRANT_SQL, isActive } from "./active";
export { entitle, hasEntitlement, listEntitlements, revokeEntitlement } from "./entitlements";
export {
  grantAllOrgPermissions,
  grantAllTeamPermissions,
  grantOrgPermission,
  grantTeamPermission,
  grantTeamScopeOrgPermission,
  grantTeamScopePermission,
  listEffectiveOrgPermissionsForAccount,
  listEffectiveTeamPermissionsForAccount,
  listOrgPermissionsForAccount,
  listTeamPermissionsForAccount,
  listTeamScopeOrgPermissions,
  listTeamScopePermissions,
  revokeOrgPermission,
  revokeTeamPermission,
  revokeTeamScopeOrgPermission,
  revokeTeamScopePermission,
  setOrgPermissionsForAccount,
  setTeamPermissionsForAccount,
  setTeamScopeOrgPermissions,
  setTeamScopePermissions,
} from "./grant-templates";
export {
  getOrgIdForTeam,
  grant,
  hasGrant,
  listAccountIdsForOrgAdmin,
  listAccountIdsForTeam,
  listGrantScopeIdsForResource,
  listGrantsForScope,
  listTeamIdsForOrg,
  revokeActiveGrantsForScopeFeature,
  revokeAllGrantsForTeamScope,
  revokeAllGrantsReferencingOrg,
  revokeAllGrantsReferencingTeam,
  revokeGrant,
  userHasAnySessionParticipantGrant,
  userHasAnyTeamMemberGrant,
} from "./grants";
export type { AuthAction, AuthResource } from "./policy";
export {
  accountScope,
  canContributeToSessionKg,
  canContributeToTeamKg,
  canCreateSession,
  canEditOrg,
  canEditTeam,
  canManageOrgPermissions,
  canManageSession,
  canManageTeamPermissions,
  canReadPersonalKg,
  canReadSessionKg,
  canReadThread,
  canViewSession,
  canWriteFacilitationThread,
  enforce,
  Feature,
  grantOrgAdmin,
  grantPersonalKgReader,
  grantSessionAdmin,
  grantSessionCreatorAccess,
  grantSessionFacilitation,
  grantSessionParticipant,
  grantSessionReader,
  grantTeamAdmin,
  grantTeamContributor,
  grantTeamMember,
  grantTeamOrgMembership,
  grantTeamSessionAdmin,
  grantTeamSessionFacilitation,
  grantTeamSessionParticipant,
  grantThreadAccess,
  hasDirectSessionGrant,
  hasFacilitationAccess,
  hasOrgAdminGrant,
  hasOrgPermission,
  hasSessionAccess,
  hasTeamAdminGrant,
  hasTeamContributorGrant,
  hasTeamPermission,
  isSessionFacilitator,
  ResourceType,
  revokeOrgAdmin,
  revokePersonalKgReader,
  revokeSessionFacilitation,
  revokeSessionParticipant,
  revokeSessionReader,
  revokeTeamAdmin,
  revokeTeamContributor,
  revokeTeamMember,
  revokeTeamSessionFacilitation,
  revokeTeamSessionParticipant,
  ScopeType,
  teamScope,
  userBelongsToOrg,
} from "./policy";
export { ensureAuthzSchema } from "./schema";
export type { EntitlementRecord, GrantRecord, ResourceRef, ScopeRef } from "./types";
